### ISSUE TITLE
Facebook Connect problem

### ISSUE THREAD

**Issue by thatspeedykid** [SocialEngine/phpv4-issues#42]
Invalid Scopes: offline_access. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

help I have the settings made correctly

**Comment by shivani2910** [comment]
Hi @thatspeedykid,

There have been some recent modifications made by Facebook in their integration API. To make your website compatible with those changes, please do below changes at your end:

Please open file ```"/application/modules/User/controllers/AuthController.php"``` and search for the below code around line no. 753:

```php
'offline_access',
```
Then replace the above code with the below code or comment it:

```php
//'offline_access',
```

We hope your problem will be resolved doing this. Also, we've forwarded this issue to our development team so that you do not face this again in future after upgrading SocialEngine.

Best Regards,
Shivani

**Comment by thatspeedykid** [comment]
One more bug to report, When I upgrade my social engine, it will add a section to the sign up that has to be removed from the following line:
Applications>Modules>User>Form>Signup> account.php

 // Element: name (trap)
$this->addElement('Text', 'name', array(
      'class' => 'signup-name',
      'label' => 'Name',
      'validators' => array(
	      array('StringLength', true, array('max' => 0)))));

    $this->name->getValidator('StringLength')->setMessage('An error has occured, please try again later.');

I fixed by doing the following:

 // Element: name (trap)
    /*$this->addElement('Text', 'name', array(
      'class' => 'signup-name',
      'label' => 'Name',
      'validators' => array(
	      array('StringLength', true, array('max' => 0)))));

    $this->name->getValidator('StringLength')->setMessage('An error has occured, please try again later.');*/

This error happens when users try and sign up mobile It puts out a name validator calling out to no where. I have noticed that I have had to fix this issue every new upgrade, so hopefully next update yall get this in check. 

thanks for the other fix!

**Comment by jdouk69** [comment]
Thank you, this worked for one of the permissions but if I disable the other permission then the feed will not work here is my full error




Warning

Invalid Scopes: publish_stream, offline_access. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.f...gin/permissions

**Comment by Anshuse** [comment]
Hi @thatspeedykid ,

If you'll signup on your site using direct URL www.example.com/signup then you'll not face this issue on your site. If you're trying to signup on site from Landing Page and there you've used some third party widgets then we suggest you to please contact the developer of respective widget.

If you're facing any issue regarding sign up using core widgets and core features of SocialEngine then you may contact our support staff along with your site details.

Best Regards,
Anshu

**Comment by Anshuse** [comment]
Hi @jdouk69 ,

The permission "publish_stream" no longer supported on Facebook. The new permission is called "publish_actions". It seems that you're using an old version of SocialEngine and so, we suggest you to upgrade SocialEngine to latest version and then make the required changes mentioned above to resolve offline_access permission issue.

If you don't want to upgrade SocialEngine yet then you may do the below changes at your end:

Please open file "/application/modules/User/controllers/AuthController.php" and search for the below code around line no. 753:

```php
'offline_access',
```
Then replace the above code with the below code or comment it:

```php
//'offline_access',
```

2. At the same place, you'll find below code:

```php
publish_stream
```
Now, replace above with below one:

```php
publish_actions
```
Please note that, we've provide above changes just to help you out and we will suggest you to upgrade SocialEngine to latest version.

Best Regards,
Anshu

**Comment by jkwas** [comment]
I've already applied all the suggested fixes here, and I'm still getting that pop up whenever I click on FB on Social Engine. The pop up: 

"Warning

Invalid Scopes: publish_stream, offline_access. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.f...gin/permissions"

Any other ideas?

**Comment by myetter37** [comment]
SocialEngine PHP version 4.8.9 has been released, and this issue has been fixed in that release.

**Comment by jdouk69** [comment]
I have a few customization on my site how much would you guys charge me to upgrade from 4.80 4.89 and include all the customizations in the code?

Thank you
Jim
