### ISSUE TITLE
Browse members not using signup data in user_fields_values , instead creates duplicate data for user_field_search, making users unsearchable based on hide or show questions on browse members page

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#592]
See comments below as identified issue via testing

**Comment by poeticjustice** [comment]
This is such a weird and annoying bug

I have a question Tattooed Yes or No (single select question)

then there is a multi-select question asking tattoo locations.

I searched Neck from the secondary layered question

It displayed 2 users, but I know there is more

Compare two profiles

User A and User B

both have tattoos on Neck, both selected Yes to tattooed question, both selected Neck in the multi-select question...... but when hitting search, it only shows User A and others who selected Neck except User B

Some users are not showing in search even tho there data matches the search.... whats going on SE???????

**Comment by poeticjustice** [comment]
Before asking, No user is'nt hidden from search because in another profile field called unique features, there is multi-select and one question is Heavily Tattooed..... if select that. User B is displayed.... this is based on not selecting an answer for tattooed question

**Comment by poeticjustice** [comment]
More investigation to above now work this one out

So I went to the profile of USER B, 
On his profile he has Yes to Tattooed, the secondary question has a list of tattoo locations
he has Neck, Upperarm, and Forearm selected.
I see it in his profile fields, even if i look at the edit profile details as admin i see it selected.....

Now explain this part.

I look in the MySQL database, i look in engine4_user_fields_search
I find that users ID..... I identify the field ID for tattoo locations which is field_77

guess what........ for User B, under Field 77 , it says NULL

How is that even possible, his profile says Neck, Upperarm, and Forearm selected.

But its NULL

So as admin, I logged in, deselected them and saved, then i reselected them and hit save..... guess what, it now has under field 77 for that user , 129,136,140 which is the option ID for Neck, Upperarm, and Forearm

NOW WTF how is this even possible, MAJOR BUG

**Comment by Elshara** [comment]
Non core feature. Might require dependent fields to fix.
Why don't you ask Donna see if a beta becomes available in the next month or so.

**Comment by poeticjustice** [comment]
@Elshara  Non Core feature??? this is using social engines core profile questions.

I have begged everyone at Social Engine to test on staging server 4.9, dunno if it will happen tho

**Comment by Elshara** [comment]
I hope to prove you wrong but in all honesty I don't think I can. I
believe it will have to be looked into first, before it could be
added.

**Comment by poeticjustice** [comment]
@Elshara there is something majorly wrong

**Comment by Elshara** [comment]
I know.

**Comment by poeticjustice** [comment]
I think the issue is
Profile Questions

Example of the problem what i think is the issue.

Admin sets up profile questions Skills (Not shown on browse members).
User Signs up
User enters skills
more members sign up
more users enters skills
Admin decides to show skills searchable on browse members
(Skills added to browse members)
Everyone user who signed up before Admin adding this to browse members, is unsearchable for them skills.

**Comment by poeticjustice** [comment]
Confirm how to replicate this bug or flaw

Use Gender profile question set to (Hide on browse members)
Sign up and select a Gender - for this example signup as Male
Now log in as Admin and click Edit Gender question (Set to show on browse members)
Now goto browse members
Search Male

it will return with NO members found.

another test could be this

Gender profile question originally set to (show on browse members)
Sign up and select a Gender - for this example signup as Male
Search browse members, goto Gender and select Male
Male users will show up
Goto profile questions as admin
set Gender to (Hide on browse members)
save
then edit it again so Gender is (Show on browse members)
Save
Goto browse members, select gender, set to Male............... No Males will ever be suggested.................... unless they signup after doing this exercise

**Comment by poeticjustice** [comment]
Here is a video http://sendvid.com/8apytcfd
or download video here https://we.tl/BZzjHcg0ry

I believe the issue i have detailed out here, was a bug raised back in April 2015 that was closed and not looked into 
https://github.com/SocialEngine/phpv4-issues/issues/24

SE for browse members is NOT searching the profile fields of each user, but creating a new database in engine4_user_fields_search, but based on the hide on browse members page / show on browse members page.

THIS KILLS ALL SEARCH FEATURES IN BROWSE MEMBERS, as from the very start everything needs to be set to show on browse members page. If you so much as accidently hide, or hide from testing purposes, it deletes all records of that field, which then becomes unsearchable when you set back to SHow on browse members!!!!!!!!!!!!!!!

extract from https://www.socialengine.com/features/php/core

Browse & Search
SocialEngine allows members to easily navigate your site, discover new content, and find specific posts.
Browse members
Members (and optionally visitors) can browse through your entire member list. Results can be filtered by profile information, like location, age, gender, height, occupation, etc. You can also choose to show only members that have a photo and members that are currently online.

**Comment by Elshara** [comment]
I responded in the other thread.

**Comment by DonnaScriptTechs** [comment]
Hi! Thanks for posting your issues and concerns. This sounds like your other bug that is confirmed already. Is it the same or similar to that one? If so, we are already working on fixing that one. It is also quite possible that issues that are similar to the other bug would resolve once that bug is fixed. 

Please note that we do check each bug so it is not necessary to tag all of us. Our team won't skip over a bug report. :)

**Comment by poeticjustice** [comment]
Hi @DonnaScriptTechs Nope this is totally unrelated to the 2 previous bugs.

This is something more major than them 2 issues, and how the search of members is stored and not pulling the users actual profile answers.

see #593 as ive discovered This and that are connected

Basically to sum it up when a user signs up, all the data they enter gets saved to the MySQL for that user  in user_fields_values

But search in browse members is not searching for that data in user_fields_values, for search its generating duplicate entries for each user purely for the browse function in user_field_search,

so anything shown or hide on browse members, deletes or NULLs the entries, 

Example your starting out on SE, your gaining members but as still low numbers, you dont want users seeing search functions on browse members so you hide them all, hide gender blah blah

regardless Gender is shown already on sign up

Now you have 1000 members, so you decide to show gender question on browse members


10 male users sign up after you set gender to show on on browse members...

Now when you search browse members, and search male..... only them 10 users will show..... none of the 1000 previous, this could kill your social network, its not using users data.

check my video , your see ;) http://sendvid.com/8apytcfd

I can post pics of the MySQL to back up everything ive mentioned

**Comment by DonnaScriptTechs** [comment]
Hi,

It's not necessary to post the MySQL data. I believe you are having an issue here. What I am wondering, and our technicians will need to check, is whether this is related. It is hard to tell from just the outside. To see if they are related, the code needs to be checked as that's the only place to tell. 

I'm sure we'll check each bug to see though, and respond accordingly once our technicians get to these posts. We would definitely want to address any bug issues if found.

**Comment by poeticjustice** [comment]
![phpad](https://cloud.githubusercontent.com/assets/19233272/23867179/f9bfaa8e-0812-11e7-81c1-d332e8768ce5.jpg)
![searphpad](https://cloud.githubusercontent.com/assets/19233272/23867184/fe0daab4-0812-11e7-8187-a6f1a2a12314.jpg)

See two images, and how its set up first image is MySqL for users and everything they enter

Then there is a field specifically for browse members which doesnt pull the data from the users, instead it duplicates all entries from signup and forms its own separate database, ready for everything to go wrong

**Comment by poeticjustice** [comment]
Just response to the above @DonnaScriptTechs 
"I believe you are having an issue here"

This is an issue everyone is having, and don't realise! 

Everyone believes brows members is pulling in from their field_values thats created on signup

No one is aware that it doesnt do this and infact a separate file is duplicated for certain fields

**Comment by gsf00001** [comment]
@poeticjustice "This is an issue everyone is having, and don't realise!"

And one of the reasons many of us ADMINs don't realize it is we use so little of SE out-of-the-box, sad to say.  This may be one of the reaons why so few ADMINs notice or post SE bugs.  For example, I don't use SE blogs, video, chat, themes, groups, events, mobile, or forums.  I only use Albums because my SEAO Plugin requires it.  So for me, basically, I probably wouldn't ever notice any bugs in 8 or so SE Modules because they are all disabled, and I use other Dev's Plugins for every one of those.  Even some inherent features/functionality (ie. not modules) of SE (such as Members) have been replaced on my site by 3rd-Party Plugins (such as SEAO Advanced Members).  

And as far as support goes, I don't bother with SE support because it's quite expensive (more than double what I pay SEAO for support - and I have to have SEAO support anyway to support their Plugins (of which I have almost every one), so it's almost as if SE support is free for me through SEAO).  

My guess is that many other ADMINs are in the same boat as me - which is why they either don't notice issues, or use someone other than SE to resolve SE issues.  This could explain why so few SE ADMINs post bugs - or any type of posts for that matter, and why it seems there are so few ADMINs out there.

**Comment by DonnaScriptTechs** [comment]
Hi,

I wasn't implying that only you are having this issue. Sorry if you took it that way. We'll test each of the reported issues though.

**Comment by DonnaScriptTechs** [comment]
Just tested and can confirm that the fields are NULL for the user_fields_search  if the question is changed from hidden to show on browse. 

If the user then saves their answers again, they show in the database. However, this is not saving the ones that had answers prior to changing from hidden to shown on the browser members page.

**Comment by Elshara** [comment]
Hmm

**Comment by Elshara** [comment]
hmm

**Comment by poeticjustice** [comment]
Thanks for testing this @DonnaScriptTechs It was bugging me why i was missing 300 people from browse members, when searching a gender.

And to note, this is a separate issue to the other issues mentioned that revolve around profile questions on mobile devices auto selecting top value, and the other issue regarding browsing multi-check and multi-select which was not displaying users correctly

**Comment by Elshara** [comment]
Yeah. It is rather strange. I'm sure it'll be fixed soon.

**Comment by JonSimon93** [comment]
This has explained everything about my friends website that i helped my friend on, he kept asking me why the browse members wasn't finding his members even tho it is in their profile fields.

The community is not massive and is between friends, so we must have done 10 clean installs of se, only difference on last install was we showed ALL our questions on browse members prior to people joining.
Rather than showing them after all our members joined.

Im passing this page to my friend, this is ridiculous, lucky it was small community between friends as it was easy to get them to resignup each time we reinstalled.

But a community larger than 100, this is a problem, I wont buy SE myself until this is sorted.

**Comment by Elshara** [comment]
I found a related issue to this, involving search itself.

**Comment by poeticjustice** [comment]
What issue have you found @Elshara

**Comment by Elshara** [comment]
Issues posted in numbers 597 - 600

**Comment by Khushboo016** [comment]
Hi @poeticjustice, Thanks for bringing up this issue, we have added this to our internal bug tracker and will fix the same in near future. 

Thanks!

**Comment by poeticjustice** [comment]
Any chance for 4.9 as I have like 300 members who are unseatchable now @Khushboo016

**Comment by Elshara** [comment]
It's probably what he means.

**Comment by JonSimon93** [comment]
I was going to buy SE as received pre release discount which expires in 2 days.

This sounds like a big issue and i doubt i wont be buying, unless its defiantly being fixed for this 4.9 release. 2 days to buy at discounted rate so be great to confirm, search will be important to me.
@Khushboo016

**Comment by Elshara** [comment]
Suffice it to say upgrades are always free. So you don't have to buy
again as it's a one time payment.
I'd personally buy it if I were you. While you got the funds.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, @Elshara, @JonSimon93, we would like to let you know that we would try our best to include this fix in 4.9, but as the release of 4.9 is very near and all the fixes and improvements that are going to be implemented in 4.9 are ready and most of the work has been merged for the release, so it would be a bit difficult to make any new fixes now in the release, so in case if the fix cannot be made in 4.9, then we would include the fix in the later releases that would take place after 4.9. We hope you understand our point here.

Thanks & Regards!

**Comment by JonSimon93** [comment]
@Khushboo016 Hi Khushboo

I Have 2 days for pre-release discount, Im no way going to buy knowing about this flaw that was raised, because it explains something i experienced ages ago thru a friends site.
What i do ask is If this is fixed for 4.9, i want to buy the top package but I ask can you honour the 10% off (Cannot commit to spending $600 and having to wait to be addressed)

I know @Elshara says 

> Suffice it to say upgrades are always free. So you don't have to buy
again as it's a one time payment.
I'd personally buy it if I were you. While you got the funds.

But regardless of upgrades are free and to buy while i have funds, i wouldnt buy now having  understanding of a contributing factor for a friends sites downfall. 
I wouldnt buy a pack of cards if i knew i had to wait for all the face value cards to be printed then collect once sent to the shops.

some bugs can be ignored or bareable until a fix, but this is really i big factor, and it took how many releases to be found?

**Comment by Elshara** [comment]
Patience is a virtue.
Thanks for considering the bug fix in future. You're awesome. Keep up
the great work.
If it requires time to process, I understand.

**Comment by poeticjustice** [comment]
@Elshara your not helping, by being patient with bug fixes, you will have adverse effects on your traffic and return users. 

This bug is in a vital area, if you have bugs in vital areas, you will lose return users, if SE didnt have these bugs, you will be able to push your site more, and if you have more users and traffic, your increase potential revenue, which in a knock on effect will make a social engine lincencee to pay for on-going support.
If a Licencee begins making good revenue, without a shadow of doubt, you would pay monthly regardless of using SE support.
But after finding this bug, i cant push for more users now, untill addressed, and if it takes 3 months to address, the site will be dead........ so patience will get you no where, because that is the reality.

**Comment by JonSimon93** [comment]
@Elshara Patience is a virtue is not really acceptable.

If you are happy to buy a pack of cards, which is awaiting god knows how long for 16 cards to be printed and distributed.......believe me, I would not play poker round yours!!!

I wouldn't buy a car, knowing there is an issue with the brakes, but to be told they will be fixed in the future.

Im not risking $600 after knowing what this issue did to my friends site about a year ago (before we didnt know the reason why, until reading this thread), 
im not risking it after reading what @poeticjustice wrote who has current members
I cannot speand $600 to then wait.I will see if its addressed before looking at alternatives.

**Comment by gsf00001** [comment]
RE: Patience
Let's be honest - very little is perfect when it comes to many products - especially software.  I can understand wanting a specific issue addressed before purchasing.  This particular issue is not like cards (i.e. you can still use this with this bug, but you can't play cards with 16 cards missing), nor is it like risking your life buying a car w/bad brakes.  It's software - bugs are inconvenient (to what extent is usually the question), not surgery or life/death.

Yes, SE should resolve this (and other) bugs (and it seems they're doing their best on many issues, and will continue to do so).  There seems to be two primary options here: Option1) If you feel you like SE and what 3rd-Party Devs offer, you may:  A) save approx $90 now with the discount (if you believe SE will fix it now or at least 'soon after 4.9' as @Khushboo016 wrote) and get started on setting things up in the mean time, or B) wait until this particular bug is fixed before jumping in (and not save the 15% and wait until later to get things going); Option2) move onto another script.  

No script is perfect.  In about 18 months, I've got close to 500 tickets created so far with 1 particular 3rd-Party Dev, and about 150 created amongst 6-7 other Devs.  Currently, only about 15 tickets total are open.  Some Devs resolve issues in a day or two; some take many months.  The point is, whatever platform you choose will probably require patience and perseverance on your part.  I'm sure you already realize this - and you're not alone in that :)   SE (along with the many 3rd-Party Plugins) is a good platform - perfect, no (but what is) - and they're doing a lot with 4.9 (let's not argue about the timing right now).  

Your call.  Wishing you much success whatever you decide.

**Comment by JonSimon93** [comment]
yes i understand this @gsf00001 

However my friend reached out to socialengine ages ago about members not being fully searchable.

And back then something was said that maybe members opted out in privacy to be searched, admittedly we may have been vague back then because members were not showing up in browse members. It was doing our head in, and this was ages ago. things changed, some things failed .
But the site i want to build will have loads of profile questions, some of which may come later, some profile questions may be hidden in browse members, but id like to think at later data i could show the field and they instantly searchable......................

However this documented thread by the person who opened it, has fully shown and explained the issue that drove me and my friend mad.

simply saying buy it now to save $90 make me believe you dont work in sales or anything.
offering discount for pre-release without knowing whats been added or fixed is stupid.

getting started and set up is silly when you know there is a road block ahead in a area thats of big functions to my site, is just silly, issue documented gave me a headache ages ago, i assumed over time it would have been fixed since i first experienced it, im guessing it was never well documented until now.
So as a potential buyer i would like to see the issue addressed am i so wrong for that @Khushboo016 @DonnaScriptTechs or as a potential buyer am i being unreasonable which @Elshara @gsf00001 are making me feel?

**Comment by poeticjustice** [comment]
@JonSimon93 i dont think your being unreasonable.
However can everyone stop this turning into becoming a forum post with their point of views on the matter.
I personally would like it addressed .
I took so much time out to document, do images, videos etc, that i dont want to engadge it forum activity, or hear opinions on the matter, i dont want to hear people defend a company, i dont want to hear people say they wont buy the item. i dont want to see users engadging in back and forth conversations, i dont want to read people telling others what to do or not do (which is ironic as im basically saying dont do this that).

LEave this thread be now, its been raised with @Khushboo016 and @shivani2910 and @DonnaScriptTechs labelled it as a bug which i hope is addressed for 4.9 but for now peeps please stop commenting, SE doesnt need to read this pointless back and forth arguement.

**Comment by gsf00001** [comment]
@JonSimon93 
I apologize if you think I'm making you feel you're being unreasonable.  I never said that (or insulted what you were doing by saying it was silly or stupid - contrary to what you feel about my thoughts).  I specifically stated options - the decision is quite simple actually, if you believe as you believe/feel.  

And yes, I used to work in sales and owned 2 consulting firms selling approx $9mil/year, so I'm not as stupid or silly as you think.  The point is sometimes an offer is made that is acceptable, and sometimes it isn't.  Either you feel it's worth proceeding, or you feel like waiting, or you feel like moving on.  It has nothing to do with you being unreasonable or reasonable - it's simply a choice for you to make.  

==>"As far as getting started and setup is silly when you know there is a road block ahead"
If I waited until all bugs were out of SE and 3rd-Party Plugins (or any software for that matter) I would have been using computers/software for the past 35+ years or so.  There were times I jumped in and wish I hadn't and other times I'm glad I jumped in - even though there were issues.  

You're being cautious - and that's smart.  Again, I wish you success in whatever you decide (and there's no ill will to read in between the lines here, no insults or anything - I honestly wish you success whatever you decide).

**Comment by poeticjustice** [comment]
@JonSimon93 i dont think your being unreasonable.
However can everyone stop this turning into becoming a forum post with their point of views on the matter.
I personally would like it addressed .
I took so much time out to document, do images, videos etc, that i dont want to engadge it forum activity, or hear opinions on the matter, i dont want to hear people defend a company, i dont want to hear people say they wont buy the item. i dont want to see users engadging in back and forth conversations, i dont want to read people telling others what to do or not do (which is ironic as im basically saying dont do this that).

LEave this thread be now, its been raised with @Khushboo016 and @shivani2910 and @DonnaScriptTechs labelled it as a bug which i hope is addressed for 4.9 but for now peeps please stop commenting, SE doesnt need to read this pointless back and forth arguement.

**Comment by gsf00001** [comment]
Oops - now we're being told to not post.  Probably why so many people don't post about SE and learn from other's thoughts/ideas/suggestions - they're insulted and told to not post.  I get it - I'll leave.

**Comment by poeticjustice** [comment]
@gsf00001 I dont work for SE, and i have tried to help many people out on here.
Its an issue id just like addressed, but i don't want SE to have to sit thru all of the above when it doesn't add any value to the bug raised, that's all. Its simply that.
I have already engaged in forum activity in the above thread myself, and ironically doing it again now.

Enhancements posts are great for back and forth ideas, as are posts helping or asking for help......
But not those labelled as bugs, a simple - "I can confirm this bug too"  is perfect for bugs listed. thats all

**Comment by Elshara** [comment]
I'm very hurt and upset by your comments the both of you.
Social Engine does not deserve the disrespect you've shown here.

**Comment by Elshara** [comment]
When you raise an issue, and it gets answered, it is okay to show your
like or dislike of the result. But my main concern, is when you try to
blackmail or force your way into a situation, which already is trying
to do all it can to play itself out in time. You haven't given time to
let the situation play out, so I think you are wrong to try to force
the developers hand in anything related to bullying them to come to
your aid.
It may or may not be what you've intended to do. But the way you act,
has gone beyond you being a desperate person. I've overlooked the fact
you have ties with social engine piracy forum (s) because I would like
to think, to know, you mean well, and are simply expressing the fact
you are upset with the fact what you wanted, hasn't yet happened. I
tend to, based on experience, my own, trust people at their word, when
they have done nothing but proven time and time again, their word
holds true to promises they have been able to keep.
I've been a client of social engine for about 3 years now, and I've
noticed a significant effort on the behalf of social engine company to
notice and appreciate the feedback other clients have. They've opened
this git hub in honor of this commitment, so that people can share
their concerns about what they've personally felt could be improved or
changed about how the software works. Social Engine, is one of the few
companies out there, who takes customer commitment to heart. Others
being Jamroom and Boonex as well as other developers in the online
marketplace, who truly care about their business. No, social engine is
not alone in their wish to improve their product, as well as their
customer service. Yes, I have seen social engine do much better work
in terms of improving both over the past 3 years. Something I can say
to you beyond a shadow of a doubt, I've not seen many companies do
until recently. But things are starting to change from say, 5 years
ago. Corporations are shifting, everything is evolving. People are
slowly, but surely, taking into consideration feedback so that people
who care about their business, stay in business because the care is
there.
I admire your willingness to care for social engine and be passionate
about it, enough to speak out against what you feel may be an
injustice. However, I would ask, with the greatest of respect to you,
that you reconsider misconduct when you've been able to confirm
through written statement, someone who works for social engine, has
gratefully considered everything you have to say. Some developers, are
not as efficient in timely updates as others, but you have to consider
here, what all they are dealing with as well as where you fit in with
the schedule. Social Engine is fortunate enough to have many third
party vendors associated with its company by nature. I do find the
more third party developers associated with a company, the more time
the company itself takes to update its software, giving third parties
a chance to coexist in business without issues. I do feel honoring
such a commitment to a certain extent, which does not involve a core
update or change to the product itself, is the job of social engine to
consider accordingly. There are many changes currently happening
within the company to better itself. So where I am coming from here,
is simply a place of trust and care.
I've said patience is a virtue, not to upset you, but to try to show
you that I've lived through worse. I've been around the block with a
whole host of other companies, and none are as friendly as social
engine except for a few. From my experience, if you wish to read my
story, about how I've gotten into the social networking community
scene, and my time with social engine as well as with other companies,
I would be happy to share it with you.
I don't mean to bother you with my opinions if they aren't what you
wish to hear. But please try to see where I am coming from. I'm
neutral. I've learned to appreciate things because I've been without,
and it isn't fun. Money is precious, I get that. And if I had my way,
I'd personally lower the cost of Social Engine. But a company has to
survive as well. So I get where you are coming from in terms of why
what you feel is important, is so relevant to here and now. I thank
you for your effort into bringing attention to things which may have
been overlooked and do definitely prolong the service in terms of both
quality and usability. But there are better ways of achieving results
faster than duplicating issues and then seemingly to force their hand
if an issue you feel is bugging you, isn't resolved. I know what it's
like to face black mail head on, and it isn't a pretty site. It is not
a laughing or joking matter, when you feel as if you are in business
for what you don't feel you deserve. Everyone must be respected for
who they are, which is the reason why I respect social engine for the
time it requires them, to do a good job at all they are aware of, and
what they do to make such awareness an improvement as time goes on.
Continuing support of the issue at hand here, I'd like to suggest
nobody is faulting anyone for what has happened or transpired. I'd
like to believe my comments here have not hurt anyone, and if so, I
apologize.
I'm going to leave the resolution up to you. But keep in mind, the
point of view of others around you. It will show you where you can
thrive and be successful if you do so. I do not personally regard you
as someone to be upset over, and I forgive you and apologize for my
misunderstanding.

**Comment by JonSimon93** [comment]
@Elshara what are you even on about???

> I'm very hurt and upset by your comments the both of you.
> Social Engine does not deserve the disrespect you've shown here.

Where have I disrespected social engine.

And you used blackmail way to much.
How dare you say I'm blackmailing Social engine! 

Black mail is -
the action, treated as a criminal offence, of demanding money from someone in return for not revealing compromising information which one has about them.


I simply said I won't part with my hard earned money that is mine and in my bank, unless I know what's been added or addressed. 
It's my money, I have that right to know, saying I'm black mailing is unacceptable?

And who are you accusing of Social engine Priracy??

These are very big claims!!!!!

**Comment by Elshara** [comment]
Social Engine Forum (sef) is strictly a piracy forum, one of many,
which deals in the illegal distribution of social engine. Anywhere you
see "nulled software" references such activity and is punishable by
the fullest extent of the law under software piracy crimes. You
mentioned it in your introduction in to this git hub page.
By saying you're not paying for social engine until you are sure
issues are being addressed, I took your stance to mean you will be
illegally using a version of social engine until such issues get
addressed in a timely manner not honored by you when responding to the
social developers. I wasn't trying to imply you were engaging in such
activity, as to date you haven't said anything to the effect of such
where stated here in, you are doing so. However it may appear to some
people like this is what is happening. I took offense at what you were
implying because it felt like you were trying to support this activity
by saying you were not going to pay until everything you needed fixed,
actually happened.
Regarding the disrespect, it was towards my previous comment. To which
you and Daniel, were unhappy with my suggestion and in my opinion,
took things too far. I felt like you were trying to cut my suggestion
down on purpose because it wasn't what you wanted to hear. All I was
trying to point out was something which could help you in future, but
you tried to make it seem like it wasn't good enough. And that is what
I took offense to, and you haven't even given me or the software a
chance.
But I don't hold it against you personally. I just am trying to be of some use.

**Comment by JonSimon93** [comment]
So you have clearly missed me time after time some saying my friend had this issue, who had spent nearly $1000 on SE and plugins with devs, you missed when I mentioned my friend paid for support and still didn't get that support or fix which was about members not showing up, my friend paid for support to be told "no issue our end maybe they opted out for search" .... so he took this answer...... then I found the ultimate reason why to be documented right here.....

And I said I want to get SE but don't want issues he had because I helped him, and it be great to have it fixed so I don't have to experience that.....


I have said this many times, so I'm not excusing you, beacause you would have read it based on your massive replies.

And you going into piracy and explaining its punishiable etc, you are assuming so much here.

I was only on SEF because the lack of support from social engine.

In a previous post I commented on you implied you worked for SE, but I'm getting the feeling you are just a customer.

If you do however work for SE then your attitude is aweful and you have helped my decision to not go with social engine. that is only if you are a member of their team, if your a customer I can excuse you for now. 

Your suggestion of patience is a virtue is a condescending statement.

I'm done replying now.
I'm just going to contact SE directly,

Accuse me of blackmail and piracy! That is slanderous!!!

**Comment by poeticjustice** [comment]
I have 2 accounts with social engine, 2 licences and all their plugins.

I have spent over $5000 on licences, social engine solutions products and custom plugins, on webhive products, seao products ..... so if your suggesting I pirate SE products, that is not cool, because i dont.

but please people can we end this here, ass this has been raised as a bug, SE will need to review this page to fix it, and all these additional posts back and forth will not help, because they will read all this as they will  believe its additional info...........
Keep the convos flying in enhancement posts, for ideas bouncing back and forth, but once identified as a bug, leave it to SE

**Comment by Elshara** [comment]
Daniel. (poetic justice) I was never accusing you of piracy.
John Simon 93. I don't work for social engine and never said I did.
All I tried to do is welcome you to the platform and attempt to ease
your mind about other issues you mentioned, which I was a contributor
of, that I know have been responded to by people at social engine. I
was just trying to pass the word along. AS the issues I know were
being fixed in the next version, according to word passed down
directly from someone working on the team, I can reference.
Khushboo016 and donna script techs work for social engine. They've
been responding to issues lately. There are others but I forget their
names on here.
All I can do is speculate at this point. Yeah, it didn't escape my
mind John Simon 93, you were talking about your friends website. But
when you mentioned social engine forum, I made the assumption you were
getting the script and support from there and hadn't tried to contact
social engine support. I suspect only licensed clients can contact
support with official bugs because you have to pay for it, as this is
how it works on the founders community website. I believe, if you
bought a license, then if you and your friend both submitted issues
about the same thing, you'd be able to get results faster. I don't
know anything about whether your friend has a license or not, but what
I do know is social engine forum is a fan based forum selling null
scripts and the only reason why support threads appear in Google
searches from there, is because it's a public forum. But people there
do not work for social engine, so they cannot, and from my personal
opinion, do not have the expertees on hand to fix bugs even if they
wanted to. As they don't have source code access, and I assume many
people over there, are just like you, in that they are looking for
free support for a script with paid options to do the same thing, but
from its official developers.
I'm sorry you had a bad experience once in your life with social
engine support. But that's no excuse to be impatient with me and other
people. I care what you have to say, so does social engine. Now the
canned response you did receive from social engine support staff is
one I've received numerous times. I fought back. I made changes based
on feedback. I was able to get other people involved in supporting
such changes at the time. And I excepted the results that happened. I
understand what priorities are and had to learn, things take time in
order to be considered, especially because the issues here are only
raised in public, not in private. So I don't have the schedule list in
front of me to add a bug  fix there, when and or if I can not only
speculate as to whether or not they have even looked at or seen this
issue, and when I say they, I am talking about developers who have the
source code in front of them, in order to be able to fix it.
I'm not sorry about my comments of blackmail, even though those
comments were not directed at poetic justice, they were directed at
John Simon 93 specifically because I assumed some aspect of social
engine forum was involved, because it was mentioned here. If anyone
mentions piracy, there's always bound to be some sort of coup
explanation as to how they can legally get away with its being
involved in a support license. Social Engine has the right to shut you
down if your name and license is even associated with a piracy forum.
AS does any other software script out there, I've seen it happen. So
I'm only trying to protect you from having an experience, you don't
want, by trying to ensure you, up front, are honest about the
limitations associated with being anonymous if you use a site like
that. You will lose your license if you are found out being a member
on there. But that's common sense.
The only thing I can do at this point, is apologize for my
misunderstanding in the confusion I participated in, to get the both
of you upset at me, for just trying to explain what I thought was
going on. I'm only trying to help, and John Simon 93 is wrong about
whether or not it matters if I work for social engine or not. Due to
the fact some people are impatient enough to care whether or not
someone sees you as a real person, or hiding within company walls as
an employee. Just shows me how much you really care about the product,
which as a customer, I find a bit disturbing because I only wish to
care about you as my equal here. Same with the product employers we
are in service to. Regardless of our experience, you keep trying. Talk
to Donna, she is someone who is on your side but just be honest with
her about everything. Social Engine is trying to improve and I do
think it has a chance here. But you have to enforce your participation
sometimes, and there are right, and wrong ways to do so. However, I
also know because you have this stance, I have to care more about
showing you things are possible here, because I wish to ease your mind
about issues you have, instead of trying to make them appear like they
are critical enough to cause you concern or distress, as much as they
do, to the effect of resulting in madness if someone doesn't get their
way. I am just not sure how to go about doing so, which is why I tried
to show you my experience, but you weren't ready to listen, which is
fine, but I am not a god and not glad you aren't like me, because I
know you have a right to be angry, and so I won't stop you from doing
what ever it is you feel like doing, and will let you without further
complaint or intervention from me, leave you be to do so as you wish.
I agree with Daniel Poetic Justice about one thing here. We exist here
to bring issues to the attention of social engine, company workers and
customer clients alike. We do our best to help each other out and we
work together to ensure anything we face trouble with, which isn't
specific to customization needs beyond something we could all use
together, is brought forth here. Not that I'm not a supporter of
customization, but we all want to improve the product we wish to use
and admire do we not? So lets set aside this little feud and work
together here. For what it's worth, I'm sorry I let you down with what
I said. I never meant to cause any problems. And I don't believe I
have to not show emotion to mean this. I'm with you every step  of the
way here and if you need or wish for support, I will find a way to
make sure you receive it as best and as peacefully as I am able to.
Effectively, ensuring essential communication exists between letting
people know an issue is present, and making sure the result is
something we can all at least live with for the moment.
Sorry to anyone not involved in the feud who had to read this back and
forth nonsense. I never meant to start a war, or enforce anything
other than explain a truth I have lived with, as it is one we all have
to share.

**Comment by DonnaScriptTechs** [comment]
Thank you all for your contributions. @gsf00001 We do appreciate your feedback and are sorry this got out of hand while our staff was offline. 

@JonSimon93 as our staff said, we will get this fixed. It might be too late to include in this next release but should be in the one thereafter. As this is a search issue, it won't keep people from joining the site so your site should grow fine. I would anticipate it wouldn't be long for a build release if this doesn't make our 4.9. Note that we don't want to push 4.9 to a later release to get this one included. We have to fix, test internally, fix any issues from that, test again with QA and then test again with staff before releasing a fix like this. Our team can be working on fixes and have a quicker release after 4.9 releases to clients soon in the case that there isn't time to include. I have my own site on SE to open soon and this bug won't stop me from using this version.

Please refrain from further conversations in this post (other than bug updates) as it slows our staff from fixing bugs when they have to read through the dialogue. If you would like to converse about bugs, please either post at our community https://community.onsocialengine.com or for those that are not clients yet, at my forum.scripttechs.com as you can converse openly at those places or in PM messages.

We do appreciate everyone in this thread though and will update it with further info when we have some.

**Comment by Elshara** [comment]
:)

**Comment by DonnaScriptTechs** [comment]
This is fixed for our next release.
